import { UserProfile, ThemeConfig } from './types';

export const DEFAULT_THEMES: ThemeConfig[] = [
  {
    id: 'default-slate',
    name: 'Clean Slate',
    backgroundStart: '#f8fafc',
    backgroundEnd: '#e2e8f0',
    buttonBg: '#ffffff',
    buttonText: '#1e293b',
    textColor: '#0f172a',
    fontFamily: 'Inter',
  },
  {
    id: 'midnight-blue',
    name: 'Midnight',
    backgroundStart: '#0f172a',
    backgroundEnd: '#1e293b',
    buttonBg: '#334155',
    buttonText: '#f8fafc',
    textColor: '#f1f5f9',
    fontFamily: 'Inter',
  },
  {
    id: 'sunset-vibes',
    name: 'Sunset',
    backgroundStart: '#ffedd5',
    backgroundEnd: '#fed7aa',
    buttonBg: '#fb923c',
    buttonText: '#fff7ed',
    textColor: '#431407',
    fontFamily: 'Inter',
  },
  {
    id: 'forest-calm',
    name: 'Forest',
    backgroundStart: '#f0fdf4',
    backgroundEnd: '#dcfce7',
    buttonBg: '#15803d',
    buttonText: '#ffffff',
    textColor: '#052e16',
    fontFamily: 'Inter',
  },
  {
    id: 'berry-burst',
    name: 'Berry',
    backgroundStart: '#fce7f3',
    backgroundEnd: '#fbcfe8',
    buttonBg: '#be185d',
    buttonText: '#ffffff',
    textColor: '#831843',
    fontFamily: 'Inter',
  },
  {
    id: 'lavender-mist',
    name: 'Lavender',
    backgroundStart: '#f5f3ff',
    backgroundEnd: '#ede9fe',
    buttonBg: '#8b5cf6',
    buttonText: '#ffffff',
    textColor: '#4c1d95',
    fontFamily: 'Inter',
  }
];

export const INITIAL_PROFILE: UserProfile = {
  name: 'Sophie Martin',
  username: 'sophie',
  bio: 'Créatrice de contenus & Passionnée de design. ✨\nBienvenue sur mon univers numérique !',
  avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&q=80',
  phone: '',
  email: '',
  links: [
    { id: '1', title: 'Mon Portfolio', url: 'https://example.com', isActive: true },
    { id: '2', title: 'Instagram', url: 'https://instagram.com', isActive: true },
    { id: '3', title: 'Ma Boutique', url: 'https://example.com/shop', isActive: true },
    { id: '4', title: 'LinkedIn', url: 'https://linkedin.com', isActive: false },
  ],
  theme: DEFAULT_THEMES[0],
};